
FROM public.ecr.aws/lambda/python:3.11

COPY requirements.txt ./

RUN python3.9 -m pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"


COPY src/predict.py ${LAMBDA_TASK_ROOT}


CMD [ "predict.lambda_handler" ]